[features]
resolution = true
skip-lint = false

[programs.devnet]
program-roulette = "4oMFMMUBuACjVW9DPbEbgPhaT4XFqHTTP43EjFqfugqb"

[programs.localnet]
program-roulette = "4oMFMMUBuACjVW9DPbEbgPhaT4XFqHTTP43EjFqfugqb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
skip_program_id_check = true

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
