[features]
resolution = true
skip-lint = false

[programs.devnet]
program-roulette = "RoTy4VytedmLQKmsynLoSMsmsZ5g57Yet8yj5N87ecp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
