[features]
resolution = true
skip-lint = false

[programs.devnet]
program-roulette = "Rou1svrgkcuo1rBNkP1XaESrD9xRpukx2uLY5MsgK14"

[programs.mainnet]
program-roulette = "Rou1svrgkcuo1rBNkP1XaESrD9xRpukx2uLY5MsgK14"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"
skip_program_id_check = true

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
